### ISSUE TITLE
nutools v3_12_03 (e20) variant for art v3_09_03 and patch: art_root_io v1_08_03a

### ISSUE THREAD

**Issue by gavinsdavies** [NuSoftHEP/nutools#4]
NOvA is pushing forward to the `art v3_09_03` (s112 with GCC e20 qualifier) release, and in doing so uncovered a major bug that has been fixed with:
`art_root_io v1_08_03a`
`canvas_root_io v1_09_04 `

or rather with the [critic v2_08_03a bundle](https://scisoft.fnal.gov/scisoft/bundles/critic/v2_08_03a/critic-v2_08_03a.html).

Simply moving those two products forward isn't enough as there are trickle-down dependencies throughout our stack.

In particular, we request a new variant of `nutools v3_12_03`.

And the following versions of `nu` related packages that depend on the above: 
`genie v3_00_06p`
`geant4   v4_10_6_p01d`
`ppfx       v02_14_13`

and also:
`nugen        v1_15_09`
`nug4          v1_12_02`
`nuevdb      v1_06_03`
`geant4reweight   v01_13_00`

Posting issue here at your request @lgarren. Let me know if you need more information or assistance and I can provide it promptly.

**Comment by lgarren** [comment]
Thanks @gavinsdavies - that is enough to start with

**Comment by knoepfel** [comment]
@lgarren, the corresponding artdaq-core version is `v3_07_04_01`: 

https://github.com/art-daq/artdaq_core/releases/tag/v3_07_04_01

**Comment by lgarren** [comment]
The build is complete and on SciSoft: https://github.com/NuSoftHEP/nutools/releases/tag/v3_12_05
