### ISSUE TITLE
New version of ppfx v02_11_05

### ISSUE THREAD

**Issue by hgreenlee** [NuSoftHEP/nutools#5]
This is a merge request for ppfx.  Please merge branch lar_v2_11_br from the github uboone clone of ppfx (https://github.com/uboone/ppfx) into branch lar_v2_11_br of the ppfx redmine git repo.  Then tag the head of branch lar_v2_11_br as v02_11_05.

For information, the target branch is used by MicroBooNE for our MCC 9.1 production releases.

This update adds a function in class NeutrinoFluxReweight to set the random number seed. This is a nonbreaking change

**Comment by lgarren** [comment]
ppfx v02_11_05 is now installed on larsoft cvmfs.  It is part of the nulite v2_27_11a distribution.
