### ISSUE TITLE
Request nu v3_13_03 and v3_13_02c bundles with {art, canvas}_root_io dictionary definition patch

### ISSUE THREAD

**Issue by gavinsdavies** [NuSoftHEP/nutools#6]
Recently NOvA requested two separate builds of the nu bundle for upgrades in both `geant4` and `genie`.

Specifically, these bundles:

[nu v3_13_03 bundle](https://scisoft.fnal.gov/scisoft/bundles/nu/v3_13_03/nu-v3_13_03.html) (includes `genie 3_02_02a` + `geant v4_11_0_p03b`
 --> canvas_root_io v1_09_05

and earlier geant4-upgrade only, [nu v3_13_02c bundle](https://scisoft.fnal.gov/scisoft/bundles/nu/v3_13_02c/nu-v3_13_02c.html) (`geant4 v4_11_0_p03b`)
--> canvas_root_io v1_09_05

Unfortunately, we have just run into the same art::FileIndex::Element class version conflicts we've seen before, and that was resolved back then with the `critic v2_08_03a`, which at the time for the particular version of art was using canvas_root_io v1_09_04a.

@knoepfel confirms the issue and will produce `canvas_root_io v1_09_05a` with the fix...which means new nu releases for NOvA, to replace the above two existing bundles.

Once this is resolved we will then get NOvA back on the mainline art 3.13/critic 2.13 (skipping any versions prior).

Our need for these is as soon as possible. We'd like to start a campaign asap for validating the physics of geant4 and genie3.2 to make some model decisions. This patch should be the last piece in the chain.

**Comment by lgarren** [comment]
Thanks @gavinsdavies, we'll keep you updated

**Comment by lgarren** [comment]
Status report:  we have a successful build of the critic v2_08_06 stack.  This build uses squal s117a.  We have artdaq_core v3_09_06 with support for s117a.  Unless there is some unanticipated problem, you'll have a new distribution by tomorrow.

**Comment by gavinsdavies** [comment]
Amazing. Thanks for the really fast turnaround on this one too.

**Comment by lgarren** [comment]
The nu [v3_13_04](https://scisoft.fnal.gov/scisoft/bundles/nu/v3_13_04/nu-v3_13_04.html) distribution is now available on SciSoft for: 
- s117a-e20
- s117a-e20-inclxx
- s117a-e20-geant4
- s117a-c7
